import "./styles/globals.css";
import "./styles/mdx.css";
import "@repo/ui/";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { docsConfig } from "../config/docs";
import { DocsSidebarNav } from "../components/sidebar-nav";
import { ScrollArea } from "../components/scroll-area";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="border-b">
          <div className="container flex-1 items-start md:grid md:grid-cols-[220px_minmax(0,1fr)] md:gap-6 lg:grid-cols-[240px_minmax(0,1fr)] lg:gap-10">
            <aside className=" fixed top-14 z-30 -ml-2 hidden h-[calc(100vh-3.5rem)] w-full shrink-0 md:sticky md:block">
              <ScrollArea className=" h-full py-6 pr-6 lg:py-8 ">
                <DocsSidebarNav items={docsConfig.sidebarNav} />
              </ScrollArea>
            </aside>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
